spring.application.name=g22-mobility

# ── MariaDB (RDBMS) ──
# Disable the driver's attempt to use Windows Login
spring.datasource.url=jdbc:mariadb://127.0.0.1:3307/mobility_db
spring.datasource.username=g22user
spring.datasource.password=g22password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDB106Dialect

# ── MongoDB (NoSQL) ──
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=mobility_nosql
spring.data.mongodb.username=g22user
spring.data.mongodb.password=g22password
spring.data.mongodb.authentication-database=admin

# ── Server & UI ──
spring.thymeleaf.cache=false
server.port=8081