spring.application.name=g22-mobility

# ── MariaDB (RDBMS) ──
# Disable the driver's attempt to use Windows Login
spring.datasource.url=jdbc:mariadb://127.0.0.1:3307/mobility_db
spring.datasource.username=g22user
spring.datasource.password=g22password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDB106Dialect

# ── MongoDB (NoSQL) ──
spring.data.mongodb.uri=mongodb://g22user:g22password@127.0.0.1:27017/mobility_nosql?authSource=admin&authMechanism=SCRAM-SHA-256
# ── Server & UI ──

spring.thymeleaf.cache=false

server.port=8443

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=g22password
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=g22